### PR TITLE
HGL tutorial

### PR DESCRIPTION
**Pull request by mcollardanuy**
Hi @fedenanni @kasra-hosseini could you have a look at the [Libyan gazetteer tutorial](https://github.com/Living-with-machines/DeezyMatch/tree/125-hgl-tutorial/examples/libyan_gazetteer)? The order is (1) prepare_dataset.ipynb and (2) tutorial_hgl_w2v.ipynb. Thanks!

### CODE REVIEW

**Comment by kasra-hosseini** [comment]
[Intro by Valeria] is missing.

**Comment by kasra-hosseini** [comment]
In `prepare_dataset`, it says:

```
# Specify the language codes of the country, for this example: Arabic, Libyan Arabic, Berber, Domari,
# Tamasheq, Teda, Egyptian Spoken Arabic, Standard Arabic, Awjila, Italian, French, English, and Libyan
# Spoken Arabic:
toponym_languages = ["ar", "ar-LY", "ber", "rmt", "taq", "tuq", "arz", "arb", "auj", "it", "fr", "en", "ayl"]
```

Where did we get these abbreviations? (e.g., "ar", "ber", ...)

**Comment by mcollardanuy** [comment]
> In `prepare_dataset`, it says:
> 
> ```
> # Specify the language codes of the country, for this example: Arabic, Libyan Arabic, Berber, Domari,
> # Tamasheq, Teda, Egyptian Spoken Arabic, Standard Arabic, Awjila, Italian, French, English, and Libyan
> # Spoken Arabic:
> toponym_languages = ["ar", "ar-LY", "ber", "rmt", "taq", "tuq", "arz", "arb", "auj", "it", "fr", "en", "ayl"]
> ```
> 
> Where did we get these abbreviations? (e.g., "ar", "ber", ...)

From geonames, mostly [this file](https://download.geonames.org/export/dump/iso-languagecodes.txt). Others are not listed ("ar-LY") but are fields in geonames, so this is a bit messy.

**Comment by kasra-hosseini** [comment]
I close this PR as we moved all the notebooks to a new repo: `DeezyMatch_tutorials` (private for now, soon to be public)

**Pull request closed without merging**
