### PR TITLE
Results used in Fig2 of EMNLP paper

### PR DESCRIPTION
**Pull request by kasra-hosseini**
This notebook contains all the results used in Fig2 of the EMNLP paper.

### CODE REVIEW

**Comment by kasra-hosseini** [comment]
@fedenanni Could you please take a look at these notebooks whenever you have time?

**Comment by fedenanni** [comment]
Hi! I am reviewing it now using [ReviewNB](https://app.reviewnb.com/Living-with-machines/DeezyMatch/files/emnlp%2Ffig2_notebook). Tiny thing that I noticed so far, instead of having this located inside "examples", maybe I will have it in a different folder (maybe `figs/paper_figures/ `) - but really as you prefer

**Comment by kasra-hosseini** [comment]
@fedenanni Thank you for the review and sorry for the delay. I moved the notebooks to this directory: `figs/EMNLP2020_figures/fig2`. Also, added the inputs there and updated the README accordingly.

**Review by fedenanni — APPROVED** [review]
Looks great - thanks!

**Comment by kasra-hosseini** [comment]
Also added some info about the models to the notebooks: https://github.com/Living-with-machines/DeezyMatch/pull/77/commits/cfdcb581fd98cce02271ab0e76dcc5cec9a78358

**Comment by kasra-hosseini** [comment]
@fedenanni If you are happy with the changes, I will go ahead and merge?

**Comment by fedenanni** [comment]
@kasra-hosseini ah great with the added infos on the model - yes go ahead and merge it, thanks!

**Pull request merged**
